// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4a4asApkm6hESDYKtdyu2N
// Component: nc2K6qmT6T
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_boombox.module.css"; // plasmic-import: 4a4asApkm6hESDYKtdyu2N/projectcss
import * as sty from "./PlasmicFooterLeft.module.css"; // plasmic-import: nc2K6qmT6T/css

export type PlasmicFooterLeft__VariantMembers = {};

export type PlasmicFooterLeft__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterLeft__VariantsArgs;
export const PlasmicFooterLeft__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterLeft__ArgsType = {};
type ArgPropType = keyof PlasmicFooterLeft__ArgsType;
export const PlasmicFooterLeft__ArgProps = new Array<ArgPropType>();

export type PlasmicFooterLeft__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<"img">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultFooterLeftProps {
  className?: string;
}

function PlasmicFooterLeft__RenderFunc(props: {
  variants: PlasmicFooterLeft__VariantsArgs;
  args: PlasmicFooterLeft__ArgsType;
  overrides: PlasmicFooterLeft__OverridesType;
  dataFetches?: PlasmicFooterLeft__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <img
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(defaultcss.img, sty.img)}
        role={"img"}
        src={"/plasmic/boombox/images/boomboxPfpNewpng.png"}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.freeBox
        )}
      >
        {
          "Boombox makes it possible aksjfdaklsdfjsa\nasdfjkasjdfk\nasdfkjas\nasdfi"
        }
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "freeBox"],
  img: ["img"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: "img";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterLeft__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterLeft__VariantsArgs;
    args?: PlasmicFooterLeft__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFooterLeft__Fetches;
  } & Omit<PlasmicFooterLeft__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooterLeft__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooterLeft__ArgProps,
      internalVariantPropNames: PlasmicFooterLeft__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFooterLeft__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterLeft";
  } else {
    func.displayName = `PlasmicFooterLeft.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterLeft = Object.assign(
  // Top-level PlasmicFooterLeft renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicFooterLeft
    internalVariantProps: PlasmicFooterLeft__VariantProps,
    internalArgProps: PlasmicFooterLeft__ArgProps
  }
);

export default PlasmicFooterLeft;
/* prettier-ignore-end */
