// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4a4asApkm6hESDYKtdyu2N
// Component: YTcpo9mYdx
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_boombox.module.css"; // plasmic-import: 4a4asApkm6hESDYKtdyu2N/projectcss
import * as sty from "./PlasmicRow2.module.css"; // plasmic-import: YTcpo9mYdx/css

export type PlasmicRow2__VariantMembers = {};

export type PlasmicRow2__VariantsArgs = {};
type VariantPropType = keyof PlasmicRow2__VariantsArgs;
export const PlasmicRow2__VariantProps = new Array<VariantPropType>();

export type PlasmicRow2__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRow2__ArgsType;
export const PlasmicRow2__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicRow2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRow2Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

function PlasmicRow2__RenderFunc(props: {
  variants: PlasmicRow2__VariantsArgs;
  args: PlasmicRow2__ArgsType;
  overrides: PlasmicRow2__OverridesType;
  dataFetches?: PlasmicRow2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox___7Yr39)}>
        {p.renderPlasmicSlot({
          defaultContents: "Name",
          value: args.children,
          className: classNames(sty.slotChildren)
        })}
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__sQhNj)}>
        {p.renderPlasmicSlot({
          defaultContents: "Description",
          value: args.slot,
          className: classNames(sty.slotSlot)
        })}
      </div>

      {p.renderPlasmicSlot({
        defaultContents: "Usage",
        value: args.slot2,
        className: classNames(sty.slotSlot2)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRow2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRow2__VariantsArgs;
    args?: PlasmicRow2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRow2__Fetches;
  } & Omit<PlasmicRow2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRow2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRow2__ArgProps,
      internalVariantPropNames: PlasmicRow2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRow2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRow2";
  } else {
    func.displayName = `PlasmicRow2.${nodeName}`;
  }
  return func;
}

export const PlasmicRow2 = Object.assign(
  // Top-level PlasmicRow2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRow2
    internalVariantProps: PlasmicRow2__VariantProps,
    internalArgProps: PlasmicRow2__ArgProps
  }
);

export default PlasmicRow2;
/* prettier-ignore-end */
