// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { ScreenVariantProvider } from "../components/plasmic/boombox/PlasmicGlobalVariant__Screen";
import { PlasmicInvite } from "../components/plasmic/boombox/PlasmicInvite";
import { useEffect } from "react";

function Invite() {
  // Use PlasmicInvite to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicInvite are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicInvite is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  useEffect(() => {
    setTimeout(() => {
      window.location.href = "https://discord.com/oauth2/authorize?client_id=678819994250772480&permissions=36785152&scope=bot%20applications.commands";
    }, 3000)

  }, []);

  return <PlasmicInvite />;
}

export default Invite;
